from .pez_minimax_preview import NODE_CLASS_MAPPINGS as PREVIEW_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as PREVIEW_NAMES
from .pez_load_transparent import NODE_CLASS_MAPPINGS as LOAD_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LOAD_NAMES
from .pez_lora_tools import NODE_CLASS_MAPPINGS as LORA_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LORA_NAMES

NODE_CLASS_MAPPINGS = {**PREVIEW_MAPPINGS, **LOAD_MAPPINGS, **LORA_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**PREVIEW_NAMES, **LOAD_NAMES, **LORA_NAMES}

WEB_DIRECTORY = "./web"
__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]